FEATURE_WEIGHTS = {
    'baseline_score': 1,
    'has_search': 1,
    'plus1_counter': 1,
    'enters_trigger': 1,
    'dies_trigger': 1,
    'repeatable_trigger': 1,
    'token_pt_total': 1,
    'activated_limiter': 1,
    'activated_no_limiter': 2,
    'has_global': 1,
    'card_advantage': 1,
    'has_recursion_battlefield': 1,
    'has_exile_access': 1,
    'has_destroy': 1,
    'has_mass_destroy': 2,
    'has_bounce': 1,
    'has_deck_stack': 2,
    'has_minus_X': 1,
    'has_mass_minus_X': 2,
    'mana_produced': 1,
    'mana_reduction': 1,
    'has_direct_damage': 1,
    'keyword_counters': 1
}