from mtg_parser.utils.normalizer import normalize_keyword

RAW_ABILITY_WORDS = {
    'Adamant',
    'Addendum',
    'Alliance',
    'Battalion',
    'Bloodrush',
    'Celebration',
    'Channel',
    'Chroma',
    'Cohort',
    'Constellation',
    'Converge',
    'Corrupted',
    "Council's dilemma",
    'Coven',
    'Delirium',
    'Descend 4',
    'Descend 8',
    'Domain',
    'Eerie',
    'Eminence',
    'Enrage',
    'Fateful hour',
    'Fathomless Descent',
    'Ferocious',
    'Formidable',
    'Grandeur',
    'Hellbent',
    'Heroic',
    'Imprint',
    'Inspired',
    'Join forces',
    'Kinship',
    'Landfall',
    'Lieutenant',
    'Magecraft',
    'Metalcraft',
    'Morbid',
    'Pack tactics',
    'Parade!',
    'Paradox',
    'Parley',
    'Radiance',
    'Raid',
    'Rally',
    'Revolt',
    'Spell mastery',
    'Strive',
    'Sweep',
    'Tempting offer',
    'Threshold',
    'Underdog',
    'Undergrowth',
    'Valiant',
    'Will of the council',
    'Will of the Planeswalkers',
}

ABILITY_WORDS = {normalize_keyword(word) for word in RAW_ABILITY_WORDS}
